"""v0.5 Descriptor."""

from __future__ import annotations

from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from boutiques.models.common import HttpUrlStr, NonEmptyStr
from boutiques.models.v05.containers import ContainerImage
from boutiques.models.v05.environment import EnvironmentVariable
from boutiques.models.v05.errors import ErrorCode
from boutiques.models.v05.groups import Group
from boutiques.models.v05.inputs import Input
from boutiques.models.v05.outputs import Output
from boutiques.models.v05.resources import SuggestedResources
from boutiques.models.v05.tests import TestCase

TagValue = Union[str, list[str], bool]


class Descriptor(BaseModel):
    """A complete Boutiques 0.5 descriptor."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    # Required
    name: NonEmptyStr = Field(description="Tool name.")
    description: NonEmptyStr = Field(description="Tool description.")
    tool_version: NonEmptyStr = Field(alias="tool-version", description="Tool version.")
    command_line: NonEmptyStr = Field(
        alias="command-line",
        description=(
            "Template describing the tool command line. Value keys are substituted at "
            "runtime with flags and values."
        ),
    )
    schema_version: Literal["0.5"] = Field(alias="schema-version")
    inputs: list[Input] = Field(min_length=1)

    # Optional metadata
    author: Optional[NonEmptyStr] = Field(default=None, description="Tool author(s).")
    url: Optional[HttpUrlStr] = Field(default=None, description="Tool URL.")
    descriptor_url: Optional[HttpUrlStr] = Field(
        alias="descriptor-url", default=None, description="Link to the descriptor itself."
    )
    doi: Optional[NonEmptyStr] = Field(default=None, description="DOI of the descriptor.")
    tool_doi: Optional[NonEmptyStr] = Field(
        alias="tool-doi", default=None, description="DOI of the tool itself."
    )
    deprecated_by_doi: Optional[Union[NonEmptyStr, bool]] = Field(
        alias="deprecated-by-doi",
        default=None,
        description=(
            "DOI of the tool that deprecates this one, or ``true`` if deprecated "
            "without a specific replacement."
        ),
    )
    online_platform_urls: Optional[list[HttpUrlStr]] = Field(
        alias="online-platform-urls",
        default=None,
        description="Online platform URLs from which the tool can be executed.",
    )
    shell: Optional[NonEmptyStr] = Field(
        default=None,
        description="Absolute path of the shell interpreter (defaults to /bin/sh).",
    )

    # Optional execution
    container_image: Optional[ContainerImage] = Field(
        alias="container-image", default=None
    )
    environment_variables: Optional[list[EnvironmentVariable]] = Field(
        alias="environment-variables", default=None, min_length=1
    )
    groups: Optional[list[Group]] = Field(default=None, min_length=1)
    output_files: Optional[list[Output]] = Field(
        alias="output-files", default=None, min_length=1
    )
    suggested_resources: Optional[SuggestedResources] = Field(
        alias="suggested-resources", default=None
    )
    error_codes: Optional[list[ErrorCode]] = Field(
        alias="error-codes", default=None, min_length=1
    )

    # Optional auxiliary
    tests: Optional[list[TestCase]] = Field(default=None, min_length=1)
    tags: Optional[dict[str, TagValue]] = Field(
        default=None, description="Open key/value pairs describing the tool."
    )
    invocation_schema: Optional[dict[str, Any]] = Field(
        alias="invocation-schema",
        default=None,
        description="Cached JSON Schema for the invocation (generated by tooling).",
    )
    custom: Optional[dict[str, Any]] = Field(
        default=None,
        description="Tool-specific extension fields outside the standard.",
    )


# Re-export aliased forms for convenience.
__all__ = ["Descriptor"]


# Kept for parity with v05_styx, whose SubCommandType is self-referential.
Descriptor.model_rebuild()
